version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    build: .
    networks:
      - secsistema_db_network  # Adicionar a rede aqui
      - secsistema_web_network
    depends_on:
      - db

  db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'dbsec'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    networks:
      - secsistema_db_network  # Adicionar a mesma rede aqui
    ports:
      - "3307:3306"
  
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - secsistema_web_network
    depends_on:
      - appseed-app

networks:
  secsistema_db_network:
    driver: bridge
  secsistema_web_network:
    driver: bridge
