version: '3.8'

services:
  appseed-app:
    build:
      context: /home/alexandre/Documents/sec-django/django-datta-able
    container_name: appseed_app
    restart: always
    networks:
      - db_network
      - web_network
  
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - /home/alexandre/Documents/sec-django/django-datta-able/nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
  
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbsec
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network
      - web_network

networks:
  db_network:
    driver: bridge
    external: true
  web_network:
    driver: bridge
    external: true

volumes:
  mysql_data: {}
