# Generated by Django 3.2.11 on 2022-08-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0002_alter_edital_id_edital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='id_programa_edital',
        ),
    ]
