# Generated by Django 4.2.1 on 2023-06-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0003_remove_edital_id_programa_edital'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='edital',
            table='EDTL_edital',
        ),
    ]
