# Generated by Django 4.2.1 on 2023-06-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nte', '0002_alter_nte_telefone_nte'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nte',
            table='NTE_nte',
        ),
    ]
