# Generated by Django 3.2.11 on 2022-07-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculdade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculdade',
            name='cnpj_faculdade',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='faculdade',
            name='telefone_faculdade',
            field=models.CharField(max_length=15),
        ),
    ]
