# Generated by Django 4.2.1 on 2023-06-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculdade', '0002_auto_20220720_2000'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculdade',
            table='FACU_faculdade',
        ),
    ]
