# Generated by Django 4.2.1 on 2023-06-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='programa',
            table='PROG_programa',
        ),
    ]
