# Generated by Django 4.2.1 on 2023-06-03 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0004_alter_edital_table'),
        ('programa', '0002_alter_programa_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='edital_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edital', to='edital.edital'),
        ),
    ]
