# Generated by Django 3.2.11 on 2022-07-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0006_alter_estagiario_cpf_estagiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='bairro_estagiario',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='genero_estagiario',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='matricula_estagiario',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='nis_pis_estagiario',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='numero_estagiario',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='raca_estagiario',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='situacao_estagiario',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='telefone_estagiario',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='turno_estagiario',
            field=models.CharField(max_length=10),
        ),
    ]
