# Generated by Django 3.2.11 on 2022-07-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0007_auto_20220707_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='nome_estagiario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='nome_responsavel_estagiario',
            field=models.CharField(max_length=100),
        ),
    ]
