# Generated by Django 3.2.11 on 2022-07-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0009_alter_estagiario_nome_estagiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='nome_estagiario',
            field=models.CharField(max_length=100),
        ),
    ]
