# Generated by Django 3.2.11 on 2022-08-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('programa', '0001_initial'),
        ('edital', '0003_remove_edital_id_programa_edital'),
        ('estagiario', '0011_alter_estagiario_rg_estagiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='id_cursos_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curso', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='id_edital_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edital', to='edital.edital'),
        ),
        migrations.AddField(
            model_name='estagiario',
            name='id_programa_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programa', to='programa.programa'),
        ),
    ]
