# Generated by Django 3.2.11 on 2022-08-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0012_auto_20220808_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estagiario',
            old_name='id_cursos_estagiario',
            new_name='curso_estagiario',
        ),
        migrations.RenameField(
            model_name='estagiario',
            old_name='id_edital_estagiario',
            new_name='edital_estagiario',
        ),
        migrations.RenameField(
            model_name='estagiario',
            old_name='id_programa_estagiario',
            new_name='programa_estagiario',
        ),
    ]
