# Generated by Django 3.2.11 on 2022-08-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSec_sede', '0003_alter_sede_nome_sede'),
        ('estagiario', '0013_auto_20220808_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='sede_estagiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sede_estagiario', to='sistemaSec_sede.sede'),
        ),
    ]
