# Generated by Django 4.2.1 on 2023-06-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0014_alter_estagiario_sede_estagiario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estagiario',
            table='ESTA_estagiario',
        ),
    ]
