# Generated by Django 4.2.1 on 2023-06-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0016_remove_estagiario_edital_estagiario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='sede_estagiario',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='supervisor_estagiario',
        ),
    ]
