# Generated by Django 4.2.1 on 2023-06-04 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0006_alter_supervisor_table'),
        ('sistemaSec_sede', '0006_remove_sede_id_nte_sede'),
        ('estagiario', '0017_remove_estagiario_sede_estagiario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede_Supervisor_Estagiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSES_id_estagiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SSES_id_estagiario', to='estagiario.estagiario')),
                ('SSES_id_sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SSES_id_sede', to='sistemaSec_sede.sede')),
                ('SSES_id_supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SSES_id_supervisor', to='supervisor.supervisor')),
            ],
        ),
    ]
