# Generated by Django 4.2.1 on 2023-06-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0018_sede_supervisor_estagiario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sede_Supervisor_Estagiario',
        ),
    ]
