# Generated by Django 4.2.1 on 2024-01-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiario', '0020_sede_supervisor_estagiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagiario',
            name='rg_estagiario',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='estagiario',
            name='semestre_estagiario',
            field=models.IntegerField(null=True),
        ),
    ]
