# Generated by Django 3.2.11 on 2022-07-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSec_sede', '0002_alter_sede_telefone_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='nome_sede',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
