# Generated by Django 4.2.1 on 2023-06-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSec_sede', '0003_alter_sede_nome_sede'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sede',
            table='Sede',
        ),
    ]
