# Generated by Django 4.2.1 on 2023-06-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSec_sede', '0004_alter_sede_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sede',
            table='SEDE_sede',
        ),
    ]
