# Generated by Django 4.2.1 on 2023-06-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSec_sede', '0005_alter_sede_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='id_nte_sede',
        ),
    ]
