# Generated by Django 3.2.11 on 2022-07-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_rename_id_sede_supervisor_supervisor_sede_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='telefone_supervisor',
            field=models.CharField(max_length=15),
        ),
    ]
