# Generated by Django 3.2.11 on 2022-08-17 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaSec_sede', '0003_alter_sede_nome_sede'),
        ('supervisor', '0004_alter_supervisor_telefone_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='sede_supervisor',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='sede_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sede_supervisor', to='sistemaSec_sede.sede'),
        ),
    ]
