# Generated by Django 4.2.1 on 2023-06-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0005_auto_20220817_1637'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supervisor',
            table='SUPE_supervisor',
        ),
    ]
