# Generated by Django 4.2.1 on 2023-06-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0006_alter_supervisor_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='sede_supervisor',
        ),
    ]
